@startuml add_right
start
:<Авторизация>;
:<Выбор нужного пункта из меню>;
:<Ввод названия права>;
:<Ввод описания права>;
:Получение из БД данных о других правах]
if (У пользователя есть право на создание права?) then (Да)
  if (Введенное название права уже есть в системе?) then (Да)
    :<Вывод ошибки: название должно быть уникальным>;
    stop
  else (Нет)
    :Сохранение нового права в БД]
    :<Вывод успеха>;
    stop
  endif
else (Нет)
  :<Вывод ошибки: недостаточно прав>;
  stop
endif
@enduml