@startuml del_pos
start
:<Авторизация>;
:<Выбор нужного пункта из меню>;
:<Ввод названия нужной должности>;
:Получение из БД данных о пользователе и должности]
if (У пользователя есть право на удаление должности?) then (Да)
  if (Введенная должность есть в системе?) then (Да)
    if (Кто-то использует эту должность?) then (Да)
      :Удаление записи из БД]
      :<Вывод успеха>;
      stop
    else (Нет)
      :<Вывод ошибки: должность всё ещё используется>;
      stop
    endif
  else (Нет)
    :<Вывод ошибки: неверный ввод>;
    stop
  endif
else (Нет)
  :<Вывод ошибки: недостаточно прав>;
  stop
endif
@enduml