@startuml usecase
left to right direction
skinparam packageStyle rectangle
actor "Сотрудник" as Aworker
package "Основное" {
usecase "Вход в систему" as Clogin
}
Aworker --> Clogin
actor "Директор" as Amanager
package "Права" {
    usecase "Создание новых прав" as Cright_cre
    usecase "Изменение данных прав" as Cright_upd
    usecase "Удаление прав" as Cright_del
}
package "Должности" {
    usecase "Создание новых должностей" as Cpos_cre
    usecase "Редактирование данных должностей" as Cpos_upd
    usecase "Удаление должностей" as Cpos_del
}
Amanager --> Cpos_cre
Amanager --> Cpos_upd
Amanager --> Cpos_del
Amanager --> Cright_cre
Amanager --> Cright_del
actor "HR" as AHR
Amanager -^ AHR
package "Сотрудники" {
    usecase "Найм сотрудников" as Cregister_naym
    usecase "Редактирование данных всех сотрудников" as Cedit_allworkers
    usecase "Увольнение сотрудников" as Cedit_allworkers_uval
}
AHR -^ Aworker
AHR --> Cedit_allworkers
AHR --> Cregister_naym
AHR --> Cedit_allworkers_uval
actor "Секретарь" as Asec
package "Отчётность" {
    usecase "Формирование отчётности" as Cotchet
}
Asec -^ Aworker
Asec --> Cotchet
@enduml